# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
pygments: true #for support {% highlight %}
highlighter: pygments
markdown: kramdown #use kramdown to parse markdown
encoding: utf-8

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "bughoho Full Stack Research"

description: "bughoho Full Stack Research, share technology post"
author:
  name: bughoho
  email: onesbug@gmail.com
  github: dbtek
  twitter: dbtek
  pinterest: asd123
  linkedin: asd123
  bio: Full Stack Research
  email_md5: 46ebc49bce685bbd1212189e9877660a

rss_path: feed.xml
categories_path: category.html
tags_path: tag.html

BASE_PATH:
